### ISSUE TITLE
2016-05-30-IO2016情報共有会.mdの確認

### ISSUE THREAD

**Issue by egugue** [ogapants/Notes#1]
Twitter上でやりとりさせて頂いた件です。
[このメモ](https://github.com/ogapants/Notes/blob/2016-05-30/20160530-IO2016%E6%83%85%E5%A0%B1%E5%85%B1%E6%9C%89%E4%BC%9A.md)を拝見しました。

__デザインについて__までは話に参加していなかったので、
それ以降について確認しました。

### 認識のずれについて
ほとんど問題なかったです。
ただ、1点。すごく細かいのですが、
> ConstraintLayoutの推奨具合はGoogle的にそこまで高くない

こちらGoogle的というよりかは、お話されていた方の個人的な意見という印象でした。
「Google的」と言ってしまうと、会社全体の意見と受け取られてしまう可能性があって危険かなと思いました。

それ以外は認識のずれはなかったです。

### 過不足について
私がまとめた[gistページ](https://gist.github.com/egugue/933e63a4b060b610323a34410ed8d7c2)があるので、これを自由にコピペしてもらって構いません。
このgistを見て、不足しているなと思った点は、
* Instant Appsにおける広告の件

くらいです。
それ以外で細かいところはありますが、細かいので。。。といった感じです。

**Comment by ogapants** [comment]
ありがとうございます！修正しました！
